"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }), (exports.KeyDefine = void 0);
const UE = require("ue");

exports.ACTION_ATTRIBUTE_LIST = {
  ModMenu: {
    NAME: "ModMenu",
    ACTION_TYPE: "ActionTypeModMenu",
    KEY_NAME: "KeyBindModMenu",
    CLEAR_NAME: "keyClearModMenu",
    TYPE_LIST: ["Toggle"],
  },
  KillAura: {
    NAME: "KillAura",
    ACTION_TYPE: "ActionTypeKillAura",
    KEY_NAME: "KeyBindKillAura",
    CLEAR_NAME: "keyClearAura",
    TYPE_LIST: ["Press", "Hold", "Toggle"],
  },
  Flight: {
    NAME: "Flight",
    ACTION_TYPE: "ActionTypeFlight",
    KEY_NAME: "KeyBindFlight",
    CLEAR_NAME: "keyClearFlight",
    TYPE_LIST: ["Toggle"],
  },
  MobVacuum: {
    NAME: "MobVacuum",
    ACTION_TYPE: "ActionTypeMobVacuum",
    KEY_NAME: "KeyBindMobVacuum",
    CLEAR_NAME: "keyClearMobVacuum",
    TYPE_LIST: ["Hold", "Toggle"],
  },
  NextTp: {
    NAME: "NextTp",
    ACTION_TYPE: "ActionTypeNextTp",
    KEY_NAME: "KeyBindNextTp",
    CLEAR_NAME: "keyClearNextTp",
    TYPE_LIST: ["Press"],
  },
  PrevTp: {
    NAME: "PrevTp",
    ACTION_TYPE: "ActionTypePrevTp",
    KEY_NAME: "KeyBindPrevTp",
    CLEAR_NAME: "keyClearPrevTp",
    TYPE_LIST: ["Press"],
  },
  MarkTp: {
    NAME: "MarkTp",
    ACTION_TYPE: "ActionTypeMarkTp",
    KEY_NAME: "KeyBindMarkTp",
    CLEAR_NAME: "keyClearMarkTp",
    TYPE_LIST: ["Press"],
  },
  QuestTp: {
    NAME: "QuestTp",
    ACTION_TYPE: "ActionTypeQuestTp",
    KEY_NAME: "KeyBindQuestTp",
    CLEAR_NAME: "keyClearQuestTp",
    TYPE_LIST: ["Press"],
  },
  NoClip: {
    NAME: "NoClip",
    ACTION_TYPE: "ActionTypeNoClip",
    KEY_NAME: "KeyBindNoClip",
    CLEAR_NAME: "keyClearNoClip",
    TYPE_LIST: ["Toggle"],
  },
  WorldSpeed: {
    NAME: "WorldSpeed",
    ACTION_TYPE: "ActionTypeWorldSpeed",
    KEY_NAME: "KeyBindWorldSpeed",
    CLEAR_NAME: "keyClearWorldSpeed",
    TYPE_LIST: ["Toggle", "Hold"],
  },
  PlayerSpeed: {
    NAME: "PlayerSpeed",
    ACTION_TYPE: "ActionTypePlayerSpeed",
    KEY_NAME: "KeyBindPlayerSpeed",
    CLEAR_NAME: "keyClearPlayerSpeed",
    TYPE_LIST: ["Toggle", "Hold"],
  },
  ReloadBuffConfig: {
    NAME: "ReloadBuffConfig",
    ACTION_TYPE: null,
    KEY_NAME: null,
    CLEAR_NAME: null,
    TYPE_LIST: ["Press"],
  },
  TreasureTeleport: {
    NAME: "TreasureTeleport",
    ACTION_TYPE: "ActionTypeTreasureTeleport",
    KEY_NAME: "KeyBindTreasureTeleport",
    CLEAR_NAME: "KeyClearTreasureTeleport",
    TYPE_LIST: ["Press"],
  },
  AlwaysShowCursor: {
    NAME: "AlwaysShowCursor",
    ACTION_TYPE: null,
    KEY_NAME: null,
    CLEAR_NAME: null,
    TYPE_LIST: ["Toggle"],
  },
  FreezeGameTime: {
    NAME: "FreezeGameTime",
    ACTION_TYPE: null,
    KEY_NAME: null,
    CLEAR_NAME: null,
    TYPE_LIST: ["Toggle"],
  },
  EchoVacuum: {
    NAME: "EchoVacuum",
    ACTION_TYPE: null,
    KEY_NAME: null,
    CLEAR_NAME: null,
    TYPE_LIST: ["Toggle"],
  },
  AutoRestartDungeon: {
    NAME: "AutoRestartDungeon",
    ACTION_TYPE: "ActionTypeAutoRestartDungeon",
    KEY_NAME: "KeyBindAutoRestartDungeon",
    CLEAR_NAME: "keyClearAutoRestartDungeon",
    TYPE_LIST: ["Toggle"],
  },
  CopyTpCordinate: {
    NAME: "CopyTpCordinate",
    ACTION_TYPE: "ActionTypeCopyTpCordinate",
    KEY_NAME: "KeyBindCopyTpCordinate",
    CLEAR_NAME: "keyClearCopyTpCordinate",
    TYPE_LIST: ["Press"],
  },
  UnstuckLoading: {
    NAME: "UnstuckLoading",
    ACTION_TYPE: "ActionTypeUnstuckLoading",
    KEY_NAME: "KeyBindUnstuckLoading",
    CLEAR_NAME: "keyClearUnstuckLoading",
    TYPE_LIST: ["Press"],
  },
  ApplyBuff: {
    NAME: "ApplyBuff",
    ACTION_TYPE: "ActionTypeApplyBuff",
    KEY_NAME: "KeyBindApplyBuff",
    CLEAR_NAME: "keyClearApplyBuff",
    TYPE_LIST: ["Press"],
  },
};
